# Generated by Django 4.2.10 on 2024-02-14 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProblema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_prob_tag', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Problema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prob_descrizione', models.CharField(max_length=400)),
                ('prob_data', models.DateField(auto_now=True)),
                ('prob_turno', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ProduttoreMacchine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reparto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_nome', models.CharField(max_length=200)),
                ('rep_stab', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDiMacchina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_m_descrizione', models.CharField(max_length=300)),
                ('tipo_m_versione', models.CharField(max_length=20)),
                ('tipo_m_produttore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestione.produttoremacchine')),
            ],
            options={
                'unique_together': {('tipo_m_descrizione', 'tipo_m_versione', 'tipo_m_produttore')},
            },
        ),
        migrations.CreateModel(
            name='Soluzione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sol_descrizione', models.CharField(max_length=500)),
                ('sol_is_risolto', models.BooleanField(default=True)),
                ('sol_problema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestione.problema')),
                ('sol_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Macchina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('macc_descrizione', models.CharField(blank=True, max_length=300, null=True)),
                ('macc_reparto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestione.reparto')),
                ('macc_tipo_macchina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestione.tipodimacchina')),
            ],
        ),
        migrations.CreateModel(
            name='DettaglioProblemaCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('det_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestione.categoriaproblema')),
                ('det_problema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestione.problema')),
            ],
        ),
    ]
